# EMAIL & PASS FOR YOUR G-ACCOUNT
PASS = ""
EMAIL = ""

# YOUR G-CLASSROOM/G-MEET URL
CLASSROOM_URL = ""

# IF NUMBER OF PEOPLE IN MEETING GETS BELOW THIS, YOU'LL LEAVE THE MEETING AUTOMATICALLY
# KEEP IT 0, IF YOU DON'T WANT TO USE THIS FEATURE
THRESHOLD_PEOPLE = 0
